<hr/>
<h3>Ajouter un nouveau produit</h3>
<form method="post" action="?page=create_product" role="form">
	<select name="subCategory_category" class="form-group">
		<optgroup label="PC">
			<option value="1">PC de bureau</option>
			<option value="2">PC portables</option>
			<option value="3">PC gamers</option>
			<option value="4">Unités centrales</option>
			<option value="5">Claviers, souris</option>
		</optgroup>
		<optgroup label="Jeux vidéo">
			<option value="6">Jeux PS4</option>
			<option value="7">Jeux Xbox One</option>
			<option value="8">Jeux PS3</option>
			<option value="9">Jeux Xbox 360</option>
			<option value="10">Jeux Wii U</option>
		</optgroup>
		<optgroup label="DVD/Blu-ray">
			<option value="11">Blu-ray action</option>
			<option value="12">Blu-ray aventure</option>
			<option value="13">DVD action</option>
			<option value="14">DVD aventure</option>
			<option value="15">Documentaires</option>
		</optgroup>
		<optgroup label="Accessoires">
			<option value="16">Connectiques</option>
			<option value="17">Ecrans</option>
			<option value="18">Manettes</option>
			<option value="19">Téléphones</option>
			<option value="20">Tablettes</option>
		</optgroup>
	</select>
	<div class="form-group">
		<label for="image">Image</label>
		<input type="url" name="img" placeholder="500x500, 25Ko max." id="image" class="form-control" required>
	</div>
	<div class="form-group">
		<label for="create_name" class="control-label">Name :</label>
		<input type="text" class="form-control" name="name" id="create_name" value="<?= (isset($name))?htmlentities($name) : "" ;?>" required>
	</div>
	<div class="form-group">
		<label for="create_description" class="control-label">Description :</label>
		<textarea name="description" id="create_description" class="form-control" cols="30" rows="10" required><?= (isset($description))?htmlentities($description) : ""; ?></textarea>
	</div>
	<div class="form-group">
		<label for="create_price" class="control-label">Prix :</label>
		<input type="text" class="form-control" name="price" id="create_price" value="<?= (isset($price))?htmlentities($price) : "" ;?>" required>
	</div>
	<div class="form-group">
		<label for="create_stock" class="control-label">Stock :</label>
		<input type="text" class="form-control" name="stock" id="create_stock" value="<?= (isset($stock))?htmlentities($stock) : "" ;?>" required>
	</div>
	<button type="submit" class="btn btn-primary pull-right">Ajouter</button>
</form>