<hr/>
<h3>Créer une nouvelle sous-catégorie</h3>
<form method="post" action="?page=sub_category&amp;id=<?=$db->lastInsertId()?>" role="form">
	<div class="form-group">
		<label for="name" class="control-label">Name</label>
		<input type="text" class="form-control" name="subCategory_name" id="name" value="" required>
	</div>
	<div class="form-group">
		<label for="description" class="control-label">Description</label>
		<textarea name="subCategory_description" id="description" class="form-control" cols="30" rows="10" required></textarea>
	</div>
	<div class="form-group">
		<label for="image" class="control-label">Image</label>
		<input type="url" name="subCategory_banner" placeholder="500x500, 25Ko max." id="image" class="form-control" required>
	</div>	
	<button type="submit" class="btn btn-primary pull-right">Create</button>
</form>