<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
       <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Se connecter <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <?php require('apps/login.php'); ?>
            <li role="separator" class="divider"></li>
            <li class="register"><a href="?page=register">Register</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <ul class="nav navbar-nav navbar-category">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Category 1 <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">SubCategory 1</a></li>
          <li><a href="#">SubCategory 2</a></li>
          <li><a href="#">SubCategory 3</a></li>
          <li><a href="#">SubCategory 4</a></li>
          <li><a href="#">SubCategory 5</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Category 2 <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">SubCategory 1</a></li>
          <li><a href="#">SubCategory 2</a></li>
          <li><a href="#">SubCategory 3</a></li>
          <li><a href="#">SubCategory 4</a></li>
          <li><a href="#">SubCategory 5</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Category 3 <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">SubCategory 1</a></li>
          <li><a href="#">SubCategory 2</a></li>
          <li><a href="#">SubCategory 3</a></li>
          <li><a href="#">SubCategory 4</a></li>
          <li><a href="#">SubCategory 5</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Category 4 <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">SubCategory 1</a></li>
          <li><a href="#">SubCategory 2</a></li>
          <li><a href="#">SubCategory 3</a></li>
          <li><a href="#">SubCategory 4</a></li>
          <li><a href="#">SubCategory 5</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Category 5 <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">SubCategory 1</a></li>
          <li><a href="#">SubCategory 2</a></li>
          <li><a href="#">SubCategory 3</a></li>
          <li><a href="#">SubCategory 4</a></li>
          <li><a href="#">SubCategory 5</a></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>