<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="?page=home"><strong>Buy!</strong></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
       <li><a href="?page=create_category">Créer une catégorie</a></li>
       <li><a href="?page=create_sub_category">Créer une sous-catégorie</a></li>
       <li><a href="?page=create_product">Ajouter un produit</a></li>
       <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Bonjour <span class="login"><?=htmlentities($currentUser->getLogin()); ?></span><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <a href="?page=profil&amp;id=<?=$_SESSION['id']?>" class="lien-profil">Voir mon profil</a> 
            <li role="separator" class="divider"></li>
             <a href="?page=logout" class="aNav"><button class="btn btn-default">Logout</button></a>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<nav class="navbar nav-category navbar-inverse">
  <div class="container-fluid sub-container">
    <ul class="nav navbar-nav navbar-category">
      <li class="dropdown col-md-3 col-sm-3 col-xs-12">
        <a href="?page=category&amp;id=1" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">PC <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="?page=sub_category&amp;id=1">PC de bureau</a></li>
          <li><a href="?page=sub_category&amp;id=2">PC portables</a></li>
          <li><a href="?page=sub_category&amp;id=3">PC gamers</a></li>
          <li><a href="?page=sub_category&amp;id=4">Unités centrales</a></li>
          <li><a href="?page=sub_category&amp;id=5">Claviers, souris</a></li>
        </ul>
      </li>
      <li class="dropdown col-md-3 col-sm-3 col-xs-12">
        <a href="?page=category&amp;id=2" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Jeux vidéos <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="?page=sub_category&amp;id=6">Jeux PS4</a></li>
          <li><a href="?page=sub_category&amp;id=7">Jeux Xbox One</a></li>
          <li><a href="?page=sub_category&amp;id=8">Jeux PS3</a></li>
          <li><a href="?page=sub_category&amp;id=9">Jeux Xbox 360</a></li>
          <li><a href="?page=sub_category&amp;id=10">Jeux Wii U</a></li>
        </ul>
      </li>
      <li class="dropdown col-md-3 col-sm-3 col-xs-12">
        <a href="?page=category&amp;id=3" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">DVD/Blu-ray <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="?page=sub_category&amp;id=11">Blu-ray action</a></li>
          <li><a href="?page=sub_category&amp;id=12">Blu-ray aventure</a></li>
          <li><a href="?page=sub_category&amp;id=13">DVD action</a></li>
          <li><a href="?page=sub_category&amp;id=14">DVD aventure</a></li>
          <li><a href="?page=sub_category&amp;id=15">Documentaires</a></li>
        </ul>
      </li>
      <li class="dropdown col-md-3 col-sm-3 col-xs-12">
        <a href="?page=category&amp;id=4" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Accessoires <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="?page=sub_category&amp;id=16">Connectiques</a></li>
          <li><a href="?page=sub_category&amp;id=17">Ecrans</a></li>
          <li><a href="?page=sub_category&amp;id=18">Manettes</a></li>
          <li><a href="?page=sub_category&amp;id=19">Téléphones</a></li>
          <li><a href="?page=sub_category&amp;id=20">Tablettes</a></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>