<div class="row">
    <div id="owl-demo" class="owl-carousel owl-theme">     
      <div class="item"><img src="public/img/fullimage1.jpg" alt=""></div>
      <div class="item"><img src="public/img/fullimage2.jpg" alt=""></div>
      <div class="item"><img src="public/img/fullimage3.jpg" alt=""></div>     
    </div>	
</div>

<div class="row">
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<h2>Catégorie à la une</h2>
		<?php require('apps/category.php'); ?>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<h2>Meilleures ventes</h2>
		<?php require('apps/list-product.php'); ?>
	</div>
</div>

<div class="row">
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<h2>Nouveautés</h2>
		<?php require('apps/list-product.php'); ?>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<h2>Les plus consultés</h2>
		<?php require('apps/list-product.php'); ?>
	</div>
</div>