<div class="row">
    <div id="owl-demo" class="owl-carousel owl-theme">     
      <div class="item"><img src="public/img/fullimage1.jpg" alt=""></div>
      <div class="item"><img src="public/img/fullimage2.jpg" alt=""></div>
      <div class="item"><img src="public/img/fullimage3.jpg" alt=""></div>     
    </div>	
</div>

<div class="row">
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<h2>Catégorie à la une</h2>
		<a href="?page=category&amp;id=2"><img class="img-category" src="public/img/category-une.jpg" alt=""></a>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<h2>Meilleures ventes</h2>
		<div class="owl-demo-product owl-carousel owl-theme">
		      <div class="item"><a href="?page=product&amp;id=1"><img src="public/img/product1.JPG" alt=""></a></div>
		      <div class="item"><a href="?page=product&amp;id=2"><img src="public/img/product2.JPG" alt=""></a></div>
		      <div class="item"><a href="?page=product&amp;id=3"><img src="public/img/product3.JPG" alt=""></a></div>
		      <div class="item"><a href="?page=product&amp;id=4"><img src="public/img/product4.JPG" alt=""></a></div>
		      <div class="item"><a href="?page=product&amp;id=5"><img src="public/img/product5.JPG" alt=""></a></div>
		      <div class="item"><a href="?page=product&amp;id=6"><img src="public/img/product6.JPG" alt=""></a></div>
		      <div class="item"><a href="?page=product&amp;id=7"><img src="public/img/product7.JPG" alt=""></a></div>
		      <div class="item"><a href="?page=product&amp;id=8"><img src="public/img/product8.JPG" alt=""></a></div>   
		</div>
	</div>
</div>

<div class="row">
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<h2>Nouveautés</h2>
		<div class="owl-demo-product owl-carousel owl-theme">
		      <div class="item"><a href="?page=product&amp;id=1"><img src="public/img/product1.JPG" alt=""></a></div>
		      <div class="item"><a href="?page=product&amp;id=2"><img src="public/img/product2.JPG" alt=""></a></div>
		      <div class="item"><a href="?page=product&amp;id=3"><img src="public/img/product3.JPG" alt=""></a></div>
		      <div class="item"><a href="?page=product&amp;id=4"><img src="public/img/product4.JPG" alt=""></a></div>
		      <div class="item"><a href="?page=product&amp;id=5"><img src="public/img/product5.JPG" alt=""></a></div>
		      <div class="item"><a href="?page=product&amp;id=6"><img src="public/img/product6.JPG" alt=""></a></div>
		      <div class="item"><a href="?page=product&amp;id=7"><img src="public/img/product7.JPG" alt=""></a></div>
		      <div class="item"><a href="?page=product&amp;id=8"><img src="public/img/product8.JPG" alt=""></a></div>   
		</div>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<h2>Les plus consultés</h2>
		<div class="owl-demo-product owl-carousel owl-theme">
		      <div class="item"><a href="?page=product&amp;id=1"><img src="public/img/product1.JPG" alt=""></a></div>
		      <div class="item"><a href="?page=product&amp;id=2"><img src="public/img/product2.JPG" alt=""></a></div>
		      <div class="item"><a href="?page=product&amp;id=3"><img src="public/img/product3.JPG" alt=""></a></div>
		      <div class="item"><a href="?page=product&amp;id=4"><img src="public/img/product4.JPG" alt=""></a></div>
		      <div class="item"><a href="?page=product&amp;id=5"><img src="public/img/product5.JPG" alt=""></a></div>
		      <div class="item"><a href="?page=product&amp;id=6"><img src="public/img/product6.JPG" alt=""></a></div>
		      <div class="item"><a href="?page=product&amp;id=7"><img src="public/img/product7.JPG" alt=""></a></div>
		      <div class="item"><a href="?page=product&amp;id=8"><img src="public/img/product8.JPG" alt=""></a></div>  
		</div>
	</div>
</div>