<div class="owl-demo-product" class="owl-carousel owl-theme">
      <div class="item"><a href=""><img src="public/img/product1.JPG" alt=""></a></div>
      <div class="item"><a href=""><img src="public/img/product2.JPG" alt=""></a></div>
      <div class="item"><a href=""><img src="public/img/product3.JPG" alt=""></a></div>
      <div class="item"><a href=""><img src="public/img/product4.JPG" alt=""></a></div>
      <div class="item"><a href=""><img src="public/img/product5.JPG" alt=""></a></div>
      <div class="item"><a href=""><img src="public/img/product6.JPG" alt=""></a></div>
      <div class="item"><a href=""><img src="public/img/product7.JPG" alt=""></a></div>
      <div class="item"><a href=""><img src="public/img/product8.JPG" alt=""></a></div>                                         
</div>