<div class="owl-demo-product" class="owl-carousel owl-theme">
      <div class="item"><a href=""><img src="public/img/product1.JPG" alt=""></a></div>
      <div class="item"></div>
      <div class="item"></div>
      <div class="item"></div>
      <div class="item"></div>
      <div class="item"></div>
      <div class="item"></div>
      <div class="item"></div>
      <div class="item"></div>
      <div class="item"></div>                                   
</div>