<!DOCTYPE html>

<html lang="en">

	<head>
		<meta charset="UTF-8">
		<title><?=htmlentities($titre)?></title>
		<!--CSS-->
		<link rel="stylesheet" href="public/style/bootstrap.min.css">
		<link rel="stylesheet" href="public/style/font-awesome/css/font-awesome.min.css">	
		<link rel="stylesheet" href="public/style/style.css"/>		
	</head>

	<body>

		<?php require('apps/header.php'); ?>
		<div class="wrap">
			<div class="main">
				<div class="container">
					<?php require('apps/content.php'); ?>
				</div>
			</div>
		</div>
		<?php require('apps/footer.php'); ?>		

	<script src="public/script/jquery-2.1.4.min.js"></script>
	<script src="public/script/bootstrap.min.js"></script>
	<script src="public/script/script.js"></script>

	</body>
</html>