<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title><?=htmlentities($titre)?></title>
		<link rel="stylesheet" href="public/style/bootstrap.min.css">
	<!--CSS-->
		<link rel="stylesheet" href="public/style/style.css"/>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
	</head>
	<body>
		<?php require('apps/header.php'); ?>
		<div class="wrap">
			<div class="main">
				<div class="container">
					<?php require('apps/content.php'); ?>
				</div>
			</div>
		</div>
		<?php require('apps/footer.php'); ?>
		

	<script type="text/javascript" src="./public/script/jquery-2.1.4.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
	<script type="text/javascript" src="./public/script/script.js"></script>

	</body>
</html>